/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ByteBitePackage;

import Conn.DatabaseConn.newpackage.DB;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.management.modelmbean.ModelMBean;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author RAM
 */
public class POSjFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(POSjFrame.class.getName());

    /**
     * Creates new form POSjFrame
     */
    public POSjFrame() {
        initComponents();
        DB.loadConnection("bytebitetestrun", "paul", "1234");
        DashBCartJList.setModel(new DefaultListModel<>());

        DashBJbtnDelList.addActionListener(e -> {
            DefaultListModel<String> model = (DefaultListModel<String>) DashBCartJList.getModel();

            int selectedIndex = DashBCartJList.getSelectedIndex();

            if (selectedIndex != -1) {
                model.remove(selectedIndex);
            } else if (model.getSize() > 0) {
                model.remove(model.getSize() - 1);
            } else {
                JOptionPane.showMessageDialog(null, "Cart is empty.");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        leftpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DashBJbtnFoods = new javax.swing.JButton();
        DashBJbtnDrinks = new javax.swing.JButton();
        DashBJbtnSides = new javax.swing.JButton();
        DashBJbtnLogOut = new javax.swing.JButton();
        centerpanel = new javax.swing.JPanel();
        NestedMiddlePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rightpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DashBJbtnCancel = new javax.swing.JButton();
        DashBJbtnCheckout = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DashBJLabelPD = new javax.swing.JLabel();
        DashBJLabelTotal = new javax.swing.JLabel();
        DashBJLabelSB = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DashBCartJList = new javax.swing.JList<>();
        DashBJbtnDelList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        leftpanel.setBackground(new java.awt.Color(204, 204, 204));
        leftpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("All Items");

        DashBJbtnFoods.setText("FOODS");
        DashBJbtnFoods.addActionListener(this::DashBJbtnFoodsActionPerformed);

        DashBJbtnDrinks.setText("DRINKS");
        DashBJbtnDrinks.addActionListener(this::DashBJbtnDrinksActionPerformed);

        DashBJbtnSides.setText("SIDES");
        DashBJbtnSides.addActionListener(this::DashBJbtnSidesActionPerformed);

        DashBJbtnLogOut.setText("Log Out");
        DashBJbtnLogOut.addActionListener(this::DashBJbtnLogOutActionPerformed);

        javax.swing.GroupLayout leftpanelLayout = new javax.swing.GroupLayout(leftpanel);
        leftpanel.setLayout(leftpanelLayout);
        leftpanelLayout.setHorizontalGroup(
            leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftpanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftpanelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(67, 67, 67))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftpanelLayout.createSequentialGroup()
                            .addComponent(DashBJbtnFoods, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43))
                        .addGroup(leftpanelLayout.createSequentialGroup()
                            .addGroup(leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DashBJbtnDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DashBJbtnSides, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(43, 43, 43)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftpanelLayout.createSequentialGroup()
                        .addComponent(DashBJbtnLogOut)
                        .addContainerGap())))
        );
        leftpanelLayout.setVerticalGroup(
            leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(DashBJbtnFoods, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(DashBJbtnDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(DashBJbtnSides, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(DashBJbtnLogOut)
                .addContainerGap())
        );

        centerpanel.setBackground(new java.awt.Color(204, 204, 204));
        centerpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        NestedMiddlePanel.setForeground(new java.awt.Color(102, 102, 102));
        NestedMiddlePanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("FOODS");

        javax.swing.GroupLayout centerpanelLayout = new javax.swing.GroupLayout(centerpanel);
        centerpanel.setLayout(centerpanelLayout);
        centerpanelLayout.setHorizontalGroup(
            centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerpanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(321, 321, 321))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerpanelLayout.createSequentialGroup()
                        .addComponent(NestedMiddlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        centerpanelLayout.setVerticalGroup(
            centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerpanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NestedMiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        rightpanel.setBackground(new java.awt.Color(204, 204, 204));
        rightpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CART");

        DashBJbtnCancel.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        DashBJbtnCancel.setText("Cancel");

        DashBJbtnCheckout.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        DashBJbtnCheckout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel7.setText("ORDER RECIEPT");

        jLabel8.setText("Oreder ID:");

        jLabel9.setText("Date:");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel10.setText("Product Discount");

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel11.setText("Sub Total");

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel12.setText("Total");

        DashBJLabelPD.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        DashBJLabelPD.setText("300");

        DashBJLabelTotal.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        DashBJLabelTotal.setText("300");

        DashBJLabelSB.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        DashBJLabelSB.setText("0");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(46, 46, 46))
            .addComponent(jSeparator5)
            .addComponent(jSeparator7)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DashBJLabelSB))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DashBJLabelTotal))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DashBJLabelPD)))
                        .addGap(17, 17, 17))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(DashBJLabelPD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(DashBJLabelSB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(DashBJLabelTotal))
                .addGap(29, 29, 29))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        DashBCartJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        DashBCartJList.addPropertyChangeListener(this::DashBCartJListPropertyChange);
        jScrollPane3.setViewportView(DashBCartJList);

        DashBJbtnDelList.setBackground(new java.awt.Color(255, 51, 51));
        DashBJbtnDelList.setText("Delete");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DashBJbtnDelList)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DashBJbtnDelList)
                .addContainerGap())
        );

        javax.swing.GroupLayout rightpanelLayout = new javax.swing.GroupLayout(rightpanel);
        rightpanel.setLayout(rightpanelLayout);
        rightpanelLayout.setHorizontalGroup(
            rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2))
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(DashBJbtnCancel)
                .addGap(6, 6, 6)
                .addComponent(DashBJbtnCheckout))
        );
        rightpanelLayout.setVerticalGroup(
            rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DashBJbtnCancel)
                    .addComponent(DashBJbtnCheckout)))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ByteBite");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(542, 542, 542))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(centerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashBJbtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnLogOutActionPerformed
        new DashBoard().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_DashBJbtnLogOutActionPerformed

    private void DashBJbtnFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnFoodsActionPerformed
    try {
    NestedMiddlePanel.removeAll();
    NestedMiddlePanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

    JScrollPane scrollPane = new JScrollPane(NestedMiddlePanel);
    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

    centerpanel.removeAll();
    centerpanel.setLayout(new BorderLayout());
    centerpanel.add(scrollPane, BorderLayout.CENTER);

    if (!(DashBCartJList.getModel() instanceof DefaultListModel)) {
        DefaultListModel<String> cartModel = new DefaultListModel<>();
        DashBCartJList.setModel(cartModel);
    }
    DefaultListModel<String> cartModel = (DefaultListModel<String>) DashBCartJList.getModel();

    String sql = "SELECT * FROM products";
    PreparedStatement pst = DB.con.prepareStatement(sql);
    ResultSet rs = pst.executeQuery();

    while (rs.next()) {
        String name = rs.getString("Productname");
        double price = rs.getDouble("ProductPrice");


        JPanel foodPanel = new JPanel(new BorderLayout());
        foodPanel.setBackground(new Color(102,102,102));

        JLabel foodLabel = new JLabel(name +"- ₱"+ price , JLabel.CENTER);
        foodLabel.setForeground(Color.WHITE); // better contrast

        JButton foodButton = new JButton("Add");

        foodButton.addActionListener(e -> {
            int a = -1;
            cartModel.addElement(name + " - ₱" + price);
            a++;
        });
        
        foodPanel.add(foodLabel, BorderLayout.CENTER);
        foodPanel.add(foodButton, BorderLayout.SOUTH);

        
        NestedMiddlePanel.add(foodPanel);
    }

} catch (SQLException e) {
        // always good to see errors
        
}

// Refresh UI
NestedMiddlePanel.revalidate();
NestedMiddlePanel.repaint();
centerpanel.revalidate();
centerpanel.repaint();
    }//GEN-LAST:event_DashBJbtnFoodsActionPerformed

    private void DashBJbtnDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnDrinksActionPerformed
        NestedMiddlePanel.removeAll();
        int i = 0;
        while (i <9) {            
                if (NestedMiddlePanel.getComponentCount() < 9) {   
            JPanel drinksPanel = new JPanel();
            drinksPanel.setBackground(new Color(102, 102, 102));
            drinksPanel.setLayout(new java.awt.BorderLayout());
            JLabel foodLabel = new JLabel("DRINKS", JLabel.CENTER);
            JButton foodButton = new JButton("Add");

            drinksPanel.add(foodLabel, java.awt.BorderLayout.CENTER);
            drinksPanel.add(foodButton, java.awt.BorderLayout.SOUTH);

            NestedMiddlePanel.add(drinksPanel);
            NestedMiddlePanel.revalidate();
            NestedMiddlePanel.repaint();
            } i++;
        }
        
    }//GEN-LAST:event_DashBJbtnDrinksActionPerformed

    private void DashBJbtnSidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnSidesActionPerformed
        NestedMiddlePanel.removeAll();
        int i = 0;
        while (i<9) {
            if (NestedMiddlePanel.getComponentCount() < 9) {
         JPanel sidesPanel = new JPanel();
         sidesPanel.setBackground(new Color(102, 102, 102));
         sidesPanel.setLayout(new java.awt.BorderLayout());
         JLabel SidesPanel = new JLabel("Sides", JLabel.CENTER);
         JButton foodButton = new JButton("Add");

         sidesPanel.add(SidesPanel, java.awt.BorderLayout.CENTER);
         sidesPanel.add(foodButton, java.awt.BorderLayout.SOUTH);

         NestedMiddlePanel.add(sidesPanel);
         NestedMiddlePanel.revalidate();
         NestedMiddlePanel.repaint();
         }
         i++;
        }
        
        
    }//GEN-LAST:event_DashBJbtnSidesActionPerformed

    private void DashBCartJListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DashBCartJListPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_DashBCartJListPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new POSjFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> DashBCartJList;
    private javax.swing.JLabel DashBJLabelPD;
    private javax.swing.JLabel DashBJLabelSB;
    private javax.swing.JLabel DashBJLabelTotal;
    private javax.swing.JButton DashBJbtnCancel;
    private javax.swing.JButton DashBJbtnCheckout;
    private javax.swing.JButton DashBJbtnDelList;
    private javax.swing.JButton DashBJbtnDrinks;
    private javax.swing.JButton DashBJbtnFoods;
    private javax.swing.JButton DashBJbtnLogOut;
    private javax.swing.JButton DashBJbtnSides;
    private javax.swing.JPanel NestedMiddlePanel;
    private javax.swing.JPanel centerpanel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel leftpanel;
    private javax.swing.JPanel rightpanel;
    // End of variables declaration//GEN-END:variables
}
