/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.newpackage;

import UI.newpackage.DashBoard;
import Conn.DatabaseConn.newpackage.DB;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.management.modelmbean.ModelMBean;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author RAM
 */
public class POSjFrame extends javax.swing.JFrame {
    private DefaultListModel<String> cartModel = new DefaultListModel<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(POSjFrame.class.getName());

    /**
     * Creates new form POSjFrame
     */
    public POSjFrame() {
        initComponents();
        setResizable(false);
        discountCombo.addActionListener(e -> calculate());
        DB.loadConnection("newbytebitedb", "root", "");
        DashBCartJList.setModel(cartModel);
        DashBJbtnDelList.addActionListener(e -> {
            DefaultListModel<String> model = (DefaultListModel<String>) DashBCartJList.getModel();

            int selectedIndex = DashBCartJList.getSelectedIndex();

            if (selectedIndex != -1) {
                model.remove(selectedIndex);
            } else if (model.getSize() > 0) {
                model.remove(model.getSize() - 1);
            } else {
                JOptionPane.showMessageDialog(null, "Cart is empty.");
            }
            calculate();
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        leftpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DashBJbtnFoods = new javax.swing.JButton();
        DashBJbtnDrinks = new javax.swing.JButton();
        DashBJbtnSides = new javax.swing.JButton();
        DashBJbtnLogOut = new javax.swing.JButton();
        centerpanel = new javax.swing.JPanel();
        NestedMiddlePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rightpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DashBJbtnCancel = new javax.swing.JButton();
        DashBJbtnCheckout = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelReciept = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DashBJLabelTotal = new javax.swing.JLabel();
        DashBJLabelSB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelDiscountAmount = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DashBCartJList = new javax.swing.JList<>();
        DashBJbtnDelList = new javax.swing.JButton();
        discountCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        leftpanel.setBackground(new java.awt.Color(204, 204, 204));
        leftpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        leftpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("All Items");
        leftpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 8, -1, -1));

        DashBJbtnFoods.setText("FOODS");
        DashBJbtnFoods.addActionListener(this::DashBJbtnFoodsActionPerformed);
        leftpanel.add(DashBJbtnFoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 69, 131, 116));

        DashBJbtnDrinks.setText("DRINKS");
        DashBJbtnDrinks.addActionListener(this::DashBJbtnDrinksActionPerformed);
        leftpanel.add(DashBJbtnDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 221, 131, 116));

        DashBJbtnSides.setText("SIDES");
        DashBJbtnSides.addActionListener(this::DashBJbtnSidesActionPerformed);
        leftpanel.add(DashBJbtnSides, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 373, 131, 116));

        DashBJbtnLogOut.setText("Log Out");
        DashBJbtnLogOut.addActionListener(this::DashBJbtnLogOutActionPerformed);
        leftpanel.add(DashBJbtnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 700, -1, -1));

        centerpanel.setBackground(new java.awt.Color(204, 204, 204));
        centerpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        centerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NestedMiddlePanel.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout NestedMiddlePanelLayout = new javax.swing.GroupLayout(NestedMiddlePanel);
        NestedMiddlePanel.setLayout(NestedMiddlePanelLayout);
        NestedMiddlePanelLayout.setHorizontalGroup(
            NestedMiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        NestedMiddlePanelLayout.setVerticalGroup(
            NestedMiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        centerpanel.add(NestedMiddlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 50, 650, 680));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("FOODS");
        centerpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 19, 57, -1));

        rightpanel.setBackground(new java.awt.Color(204, 204, 204));
        rightpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        rightpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CART");
        rightpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 8, -1, -1));
        rightpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 701, 172, 10));

        DashBJbtnCancel.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        DashBJbtnCancel.setText("Cancel");
        DashBJbtnCancel.addActionListener(this::DashBJbtnCancelActionPerformed);
        rightpanel.add(DashBJbtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 701, -1, -1));

        DashBJbtnCheckout.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        DashBJbtnCheckout.setText("Checkout");
        DashBJbtnCheckout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DashBJbtnCheckout.addActionListener(this::DashBJbtnCheckoutActionPerformed);
        rightpanel.add(DashBJbtnCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 701, -1, -1));
        rightpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 343, 172, 4));

        jPanelReciept.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel7.setText("ORDER RECIEPT");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel10.setText("Product Discount:");

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel11.setText("Sub Total:");

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel12.setText("Total");

        DashBJLabelTotal.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        DashBJLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DashBJLabelTotal.setText("0");

        DashBJLabelSB.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        DashBJLabelSB.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DashBJLabelSB.setText("0");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel4.setText("Tax:");

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("0.12");

        jLabelDiscountAmount.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabelDiscountAmount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDiscountAmount.setText("0");

        javax.swing.GroupLayout jPanelRecieptLayout = new javax.swing.GroupLayout(jPanelReciept);
        jPanelReciept.setLayout(jPanelRecieptLayout);
        jPanelRecieptLayout.setHorizontalGroup(
            jPanelRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator7)
            .addGroup(jPanelRecieptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRecieptLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DashBJLabelTotal))
                    .addGroup(jPanelRecieptLayout.createSequentialGroup()
                        .addGroup(jPanelRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRecieptLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel7))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanelRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDiscountAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(DashBJLabelSB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        jPanelRecieptLayout.setVerticalGroup(
            jPanelRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecieptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(DashBJLabelSB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDiscountAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jPanelRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(DashBJLabelTotal))
                .addGap(29, 29, 29))
        );

        rightpanel.add(jPanelReciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 353, 240, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        DashBCartJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        DashBCartJList.addPropertyChangeListener(this::DashBCartJListPropertyChange);
        jScrollPane3.setViewportView(DashBCartJList);

        DashBJbtnDelList.setBackground(new java.awt.Color(255, 51, 51));
        DashBJbtnDelList.setText("Delete");
        DashBJbtnDelList.addActionListener(this::DashBJbtnDelListActionPerformed);

        discountCombo.setBackground(new java.awt.Color(0, 255, 0));
        discountCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discount None", "Student Discount", "Senior Discount", "Pregnant Discount", "PWD Discount", "Employee Discount" }));
        discountCombo.addActionListener(this::discountComboActionPerformed);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(discountCombo, 0, 110, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DashBJbtnDelList)
                .addGap(30, 30, 30))
            .addComponent(jScrollPane3)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(DashBJbtnDelList)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(discountCombo))
                .addContainerGap())
        );

        rightpanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 39, 240, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ByteBite");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(centerpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                    .addComponent(rightpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void calculate() {
            double subTotal = 0;

            for (int i = 0; i < cartModel.getSize(); i++) {
                String item = cartModel.getElementAt(i);
                String[] parts = item.split("₱");
                try {
                    subTotal += Double.parseDouble(parts[1].trim());
                } catch (Exception ex) {}
            }

            double tax = subTotal * 0.12;

            // 🔽 GET SELECTED DISCOUNT
            String selectedDiscount = discountCombo.getSelectedItem().toString();

            double discountRate = 0;

            switch (selectedDiscount) {
                case "Discount None":
                    discountRate = 0; // 5%
                    break;
                case "Student Discount":
                    discountRate = 0.05; // 5%
                    break;
                case "PWD Discount":
                    discountRate = 0.20; // 20%
                    break;
                case "Senior Discount":
                    discountRate = 0.20; // 20%
                    break;
                case "Employee Discount":
                    discountRate = 0.05; // 5%
                    break;
                case "Pregnant Discount":
                    discountRate = 0.10; // 20%
                    break;
                default:
                    discountRate = 0;
            }

            double discount = subTotal * discountRate;
            double total = subTotal + tax - discount;

            // 🔽 DISPLAY VALUES
            DashBJLabelSB.setText(String.format("%.2f", subTotal));
            jLabelDiscountAmount.setText((int)(discountRate * 100) + "%");
            DashBJLabelTotal.setText(String.format("%.2f", total));
        }
    
    
    private void DashBJbtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnLogOutActionPerformed
        new DashBoard().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_DashBJbtnLogOutActionPerformed

    private void DashBJbtnFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnFoodsActionPerformed
    try {
            NestedMiddlePanel.removeAll();
            NestedMiddlePanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

            JScrollPane scrollPane = new JScrollPane(NestedMiddlePanel);
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

            centerpanel.removeAll();
            centerpanel.setLayout(new BorderLayout());
            centerpanel.add(scrollPane, BorderLayout.CENTER);

            if (!(DashBCartJList.getModel() instanceof DefaultListModel)) {
                DefaultListModel<String> cartModel = new DefaultListModel<>();
                DashBCartJList.setModel(cartModel);
            }
            DefaultListModel<String> cartModel = (DefaultListModel<String>) DashBCartJList.getModel();

            String sql = "SELECT * FROM foods WHERE category = 'foods'";
            PreparedStatement pst = DB.con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String name = rs.getString("foods");
                double price = rs.getDouble("price");
                String imagePath = rs.getString("path");

                // Create panel
                JPanel DrinkPanel = new JPanel(new BorderLayout());
                DrinkPanel.setBackground(new Color(102, 102, 102));
                DrinkPanel.setPreferredSize(new Dimension(180, 235));

                // 🔽 IMAGE LABEL (TOP)
                JLabel imageLabel = new JLabel();
                imageLabel.setPreferredSize(new Dimension(180, 140));

                if (imagePath != null && !imagePath.isEmpty()) {
                    ImageIcon icon = new ImageIcon(getClass().getResource("/" + imagePath));
                    Image img = icon.getImage();

                    Image scaledImg = img.getScaledInstance(
                            210, 140,   // match label size
                            Image.SCALE_SMOOTH
                    );

                    imageLabel.setIcon(new ImageIcon(scaledImg));
                }

                // 🔽 TEXT (CENTER)
                JLabel DrinkLabel = new JLabel(name + " - ₱" + price, JLabel.CENTER);
                DrinkLabel.setForeground(Color.WHITE);

                // 🔽 BUTTON (BOTTOM)
                JButton DrinkButton = new JButton("Add");

                DrinkButton.addActionListener(e -> {
                    cartModel.addElement(name + " - ₱" + price);
                    calculate();
                });

                // 🔽 ADD COMPONENTS TO PANEL
                DrinkPanel.add(imageLabel, BorderLayout.NORTH);
                DrinkPanel.add(DrinkLabel, BorderLayout.CENTER);
                DrinkPanel.add(DrinkButton, BorderLayout.SOUTH);

                NestedMiddlePanel.add(DrinkPanel);
            }

            NestedMiddlePanel.revalidate();
            NestedMiddlePanel.repaint();
            centerpanel.revalidate();
            centerpanel.repaint();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DashBJbtnFoodsActionPerformed

    private void DashBJbtnDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnDrinksActionPerformed
        try {
            NestedMiddlePanel.removeAll();
            NestedMiddlePanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

            JScrollPane scrollPane = new JScrollPane(NestedMiddlePanel);
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

            centerpanel.removeAll();
            centerpanel.setLayout(new BorderLayout());
            centerpanel.add(scrollPane, BorderLayout.CENTER);

            if (!(DashBCartJList.getModel() instanceof DefaultListModel)) {
                DefaultListModel<String> cartModel = new DefaultListModel<>();
                DashBCartJList.setModel(cartModel);
            }
            DefaultListModel<String> cartModel = (DefaultListModel<String>) DashBCartJList.getModel();

            String sql = "SELECT * FROM foods WHERE category = 'drinks'";
            PreparedStatement pst = DB.con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String name = rs.getString("foods");
                double price = rs.getDouble("price");
                String imagePath = rs.getString("path");

                JPanel DrinkPanel = new JPanel(new BorderLayout());
                DrinkPanel.setBackground(new Color(102, 102, 102));
                DrinkPanel.setPreferredSize(new Dimension(180, 235));
                
                JLabel imageLabel = new JLabel();
                imageLabel.setPreferredSize(new Dimension(180, 140));
                
                if (imagePath != null && !imagePath.isEmpty()) {
                    ImageIcon icon = new ImageIcon(getClass().getResource("/" + imagePath));
                    Image img = icon.getImage();

                    Image scaledImg = img.getScaledInstance(
                            210, 140,   // match label size
                            Image.SCALE_SMOOTH
                    );

                    imageLabel.setIcon(new ImageIcon(scaledImg));
                }
                
                JLabel DrinkLabel = new JLabel(name + "- ₱" + price, JLabel.CENTER);
                DrinkLabel.setForeground(Color.WHITE);

                JButton DrinkButton = new JButton("Add");

                DrinkButton.addActionListener(e -> {
                    cartModel.addElement(name + " - ₱" + price);
                    calculate();
                });

                DrinkPanel.add(imageLabel, BorderLayout.NORTH);
                DrinkPanel.add(DrinkLabel, BorderLayout.CENTER);
                DrinkPanel.add(DrinkButton, BorderLayout.SOUTH);

                NestedMiddlePanel.add(DrinkPanel);
            }

            NestedMiddlePanel.revalidate();
            NestedMiddlePanel.repaint();
            centerpanel.revalidate();
            centerpanel.repaint();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DashBJbtnDrinksActionPerformed

    private void DashBJbtnSidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnSidesActionPerformed
        try {
            NestedMiddlePanel.removeAll();
            NestedMiddlePanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

            JScrollPane scrollPane = new JScrollPane(NestedMiddlePanel);
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            scrollPane.setPreferredSize(new Dimension(80,400));

            centerpanel.removeAll();
            centerpanel.setLayout(new BorderLayout());
            centerpanel.add(scrollPane, BorderLayout.CENTER);

            String sql = "SELECT * FROM foods WHERE category = 'sides'";
            PreparedStatement pst = DB.con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String name = rs.getString("foods");
                double price = rs.getDouble("price");
                String imagePath = rs.getString("path");

                JPanel DrinkPanel = new JPanel(new BorderLayout());
                DrinkPanel.setBackground(new Color(102, 102, 102));
                DrinkPanel.setPreferredSize(new Dimension(180, 235));
                
                JLabel imageLabel = new JLabel();
                imageLabel.setPreferredSize(new Dimension(180, 140));
                
                if (imagePath != null && !imagePath.isEmpty()) {
                    ImageIcon icon = new ImageIcon(getClass().getResource("/" + imagePath));
                    Image img = icon.getImage();

                    Image scaledImg = img.getScaledInstance(
                            210, 140,   // match label size
                            Image.SCALE_SMOOTH
                    );

                    imageLabel.setIcon(new ImageIcon(scaledImg));
                }
                
                JLabel DrinkLabel = new JLabel(name + "- ₱" + price, JLabel.CENTER);
                DrinkLabel.setForeground(Color.WHITE);
                DrinkLabel.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
                DrinkLabel.setFont(new Font("Arial", Font.PLAIN, 12));
                
                JButton DrinkButton = new JButton("Add");
                
                DrinkButton.addActionListener(e -> {
                    cartModel.addElement(name + " - ₱" + price);
                    calculate();
                });

                DrinkPanel.add(imageLabel, BorderLayout.NORTH);
                DrinkPanel.add(DrinkLabel, BorderLayout.CENTER);
                DrinkPanel.add(DrinkButton, BorderLayout.SOUTH);

                NestedMiddlePanel.add(DrinkPanel);
            }

            NestedMiddlePanel.revalidate();
            NestedMiddlePanel.repaint();
            centerpanel.revalidate();
            centerpanel.repaint();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DashBJbtnSidesActionPerformed

    private void DashBCartJListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DashBCartJListPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_DashBCartJListPropertyChange

    private void DashBJbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnCancelActionPerformed
        DefaultListModel<String> model = (DefaultListModel<String>) DashBCartJList.getModel();
        model.clear();
        calculate();

    }//GEN-LAST:event_DashBJbtnCancelActionPerformed

    private void DashBJbtnDelListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnDelListActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_DashBJbtnDelListActionPerformed
    private boolean discountApplied = false;
    private void DashBJbtnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBJbtnCheckoutActionPerformed
   if (cartModel.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Cart is empty!");
        return;
    }

    try {
        // Loop through every item currently in the cart
        for (int i = 0; i < cartModel.getSize(); i++) {
            String itemLine = cartModel.getElementAt(i); // Format: "Burger - ₱150.0"
            
            // Split the string to get Name and Price separately
            String[] parts = itemLine.split(" - ₱");
            String itemName = parts[0].trim();
            double itemPrice = Double.parseDouble(parts[1].trim());

            // Save each specific item to the database
            saveIndividualItem(itemName, itemPrice);
        }

        // Clear UI after successful checkout
        cartModel.clear();
        calculate();
        
        JOptionPane.showMessageDialog(null, "Transaction Complete!");
        // Note: We removed the code that opens AdminDashboard so you stay on this screen.

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error during checkout: " + e.getMessage());
    }




    }//GEN-LAST:event_DashBJbtnCheckoutActionPerformed

    private void discountComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountComboActionPerformed

    /**
     * @param args the command line arguments
     */ 
    private void saveIndividualItem(String name, double price) {
        try {
            String sql = "INSERT INTO sales (`Item`, Price, Date) VALUES (?, ?, NOW())";
            java.sql.PreparedStatement pst = DB.con.prepareStatement(sql);
            
            pst.setString(1, name);
            pst.setDouble(2, price);
            pst.executeUpdate();
        } catch (java.sql.SQLException e) {
            System.out.println("DB Error: " + e.getMessage());
        }
    }

    // 2. The Main Method (Required to run the program)
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new POSjFrame().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> DashBCartJList;
    private javax.swing.JLabel DashBJLabelSB;
    private javax.swing.JLabel DashBJLabelTotal;
    private javax.swing.JButton DashBJbtnCancel;
    private javax.swing.JButton DashBJbtnCheckout;
    private javax.swing.JButton DashBJbtnDelList;
    private javax.swing.JButton DashBJbtnDrinks;
    private javax.swing.JButton DashBJbtnFoods;
    private javax.swing.JButton DashBJbtnLogOut;
    private javax.swing.JButton DashBJbtnSides;
    private javax.swing.JPanel NestedMiddlePanel;
    private javax.swing.JPanel centerpanel;
    private javax.swing.JComboBox<String> discountCombo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDiscountAmount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanelReciept;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel leftpanel;
    private javax.swing.JPanel rightpanel;
    // End of variables declaration//GEN-END:variables
}
